# Generated by Django 2.0.9 on 2018-12-24 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0003_auto_20181224_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 23, 1, 23, 167721)),
        ),
    ]
