# Generated by Django 2.0.9 on 2018-12-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0005_auto_20181224_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='user',
        ),
    ]
