# Generated by Django 2.0.9 on 2018-12-24 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0009_auto_20181225_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 31, 45, 684079)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
