# Generated by Django 2.0.9 on 2018-12-24 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0011_auto_20181225_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 37, 38, 434304)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
