# Generated by Django 2.0.9 on 2018-12-24 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0012_auto_20181225_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 50, 2, 890691)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.FileField(default=1, upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
