# Generated by Django 2.0.9 on 2018-12-24 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0013_auto_20181225_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 1, 57, 41, 420213)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.FileField(upload_to='static'),
        ),
    ]
