# Generated by Django 2.0.9 on 2018-12-25 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0020_auto_20181225_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_img2',
            field=models.CharField(default='els.fields.files.FileField>', max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 4, 52, 22, 813116)),
        ),
    ]
