# Generated by Django 2.0.9 on 2018-12-25 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0023_auto_20181225_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 4, 56, 37, 917238)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img2',
            field=models.CharField(default='<django.db.models.fields.files.FileField>', max_length=200),
        ),
    ]
