# Generated by Django 2.0.9 on 2018-12-25 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0029_auto_20181225_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 5, 49, 54, 16691)),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img',
            field=models.ImageField(upload_to='static/oyunlar/images/'),
        ),
    ]
