# Generated by Django 2.0.9 on 2018-12-25 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyunlar', '0032_auto_20181225_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 16, 4, 9, 248214)),
        ),
    ]
